### ISSUE TITLE
Generated plugin crashes when installed due to incorrect export

### ISSUE THREAD

**Issue by afahim** [eslint/generator-eslint#19]
##### What  version of generator-eslint?

1.0.2

##### What did you do?

* Installed and ran `yo eslint:plugin`.
* Didn't modify any project setup, just added a rule and tests (which passed).
* Added plugin to a project using eslint.
* Ran eslint on said project.

##### What went wrong?

ESlint resulted in this error

```
fs.js:813
  return binding.readdir(pathModule._makeLong(path));
                                    ^

Error: ENOENT: no such file or directory, scandir './rules'
```

I suspect its because requireIndex expects a `__dirname` to be passed in as well, which isn't being passed inside index.js.

**Comment by nzakas** [comment]
Can you share the full console output?

**Comment by afahim** [comment]
I just tried using it in with two different projects. Here are the console outputs

* Project A (running eslint@1.10.3)

```
> eslint --ext js,html "."

fs.js:813
  return binding.readdir(pathModule._makeLong(path));
                                    ^

Error: ENOENT: no such file or directory, scandir './rules'
    at Error (native)
    at Object.fs.readdirSync (fs.js:813:18)
    at module.exports (/Users/afahim/projects/<ProjectName>/node_modules/eslint-plugin-underscore-lodash-compatibility/node_modules/requireindex/index.js:18:20)
    at Object.<anonymous> (/Users/afahim/projects/<ProjectName>/node_modules/eslint-plugin-underscore-lodash-compatibility/lib/index.js:21:24)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

* Project B (running eslint@latest)

```
> eslint test/*.js *.js

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-underscore-lodash-compatibility". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-underscore-lodash-compatibility is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-underscore-lodash-compatibility@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by afahim** [comment]
I see that https://github.com/eslint/generator-eslint/pull/15 has already been submitted as a fix.

**Comment by nzakas** [comment]
Ah yes, this is part of why we require issues for PRs, it makes it easier to track duplicates. If you submit a PR, I can merge it in
