### ISSUE TITLE
Error when running generator

### ISSUE THREAD

**Issue by 10thfloor** [eslint/generator-eslint#48]
Running `yo eslint:plugin` produces the following error:

node/6.3.0

``` bash
module.js:442
    throw err;
    ^

Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-eslint/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by platinumazure** [comment]
Weird, it looks like `gulp-sourcemaps` is throwing that error. I'll try to take a look in the next day or two.

**Comment by platinumazure** [comment]
@10thfloor I can't reproduce this on master. Can you please provide some more information?

It would also be good to know how far you are getting in the process and how you are answering each question.

Thanks!

**Comment by platinumazure** [comment]
Ping @10thfloor, can you please answer my questions in my previous comment when you get a chance? Thanks!

**Comment by nzakas** [comment]
Closing, as there's been no response during the past 27 days.
