### ISSUE TITLE
Error: You must provide a `choices` parameter

### ISSUE THREAD

**Issue by akras14** [eslint/generator-eslint#9]
I've tried to get the generator working both on Unix and Mac, but keep running into this error when running `yo eslint:plugin`.

```
mac main: yo --version
1.4.7
mac main: yo --generators
eslint
mac main: yo eslint:plugin
? What is your name? Alex
? What is the plugin ID? test
? Type a short description of this plugin: Test


/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:579
    throw e;
          ^
Error: You must provide a `choices` parameter
    at Prompt.throwParamError (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/prompts/base.js:88:9)
    at new Prompt (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/prompts/checkbox.js:28:10)
    at PromptUI.fetchAnswer (/usr/local/lib/node_modules/yo/node_modules/inquirer/lib/ui/prompt.js:92:16)
    at /usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:4599:20
    at tryCatcher (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at InnerObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:4806:43)
    at InnerObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:567:29)
    at AutoDetachObserverPrototype.next (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:5274:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:1710:35)
    at InnerObserver.onNext (/usr/local/lib/node_modules/yo/node_modules/inquirer/node_modules/rx/dist/rx.js:3409:91)
```

Looks like inquirer is throwing an error, but not sure if it seems to work for others? I've tried older verison of yo, generator, and inquirer, and could not find a working combination.

**Comment by ilyavolodin** [comment]
Thanks for the report. I was able to reproduce this locally. Looking into it now.

**Comment by ilyavolodin** [comment]
Ahh.. looks like the last two questions are yes/no questions, checkbox style, but we are not providing `choices` should be easy to fix.
